---

- name: manage webserver
  hosts: jenkins
  gather_facts: false
  remote_user: ubuntu
  become: true
  tasks:
    - name: manage package
      package:
         name: "{{ package_name }}"
         state: present
    - name: manage service
      service:
         name: "{{ service_name }}"
         state: started
    - name: deploy site
      copy:
         src: index.html
         dest: "{{ doc_root }}"
- name: manage users
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks:
    - name: create and manage users
      user:
         name: "{{ user_name }}"
         state: present 
